### ISSUE TITLE
Permissioned denied on reading risks results in a panic

### ISSUE THREAD

**Issue by prologic** [prometheus-community/smartctl_exporter#39]
See:

```#!sh
root@vz1:~# su - smartctl_exporter
smartctl_exporter@vz1:~$ smartctl_exporter
[Warning] S.M.A.R.T. output reading error: exit status 2
[Warning] The device error log contains records of errors.
[Error] Smartctl open device: /dev/sda failed: Permission denied
[Error] smartctl returned bad data for device /dev/sda
[Warning] S.M.A.R.T. output reading error: exit status 2
[Warning] The device error log contains records of errors.
[Error] Smartctl open device: /dev/sdb failed: Permission denied
[Error] smartctl returned bad data for device /dev/sdb
[Warning] S.M.A.R.T. output reading error: exit status 2
[Warning] The device error log contains records of errors.
[Error] Smartctl open device: /dev/sdc failed: Permission denied
[Error] smartctl returned bad data for device /dev/sdc
panic: runtime error: index out of range [0] with length 0

goroutine 38 [running]:
main.(*SMARTctlInfo).mineVersion(0xc000125eb8)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/smartctlinfo.go:46 +0x942
main.(*SMARTctlInfo).Collect(...)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/smartctlinfo.go:35
main.SMARTctlManagerCollector.Collect(0xc00025c060)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/main.go:37 +0x1c1
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1(0xa20840, 0xdc8010, 0xc00025c060)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/vendor/src/github.com/prometheus/client_golang/prometheus/collector.go:90 +0x3b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/vendor/src/github.com/prometheus/client_golang/prometheus/collector.go:89 +0x75
smartctl_exporter@vz1:~$ echo $?
2
smartctl_exporter@vz1:~$
```

We _should_ maybe gracefully exit with a better error rather than panicing

**Comment by Lusitaniae** [comment]
Also we might need to document requirements better?

Looks like running smartctl_exporter from a user in the "disk" group solves some of the errors ^

**Comment by DaAwesomeP** [comment]
On Debian 11 adding the user to the `disk` group does not appear to give enough access to smartctl.

**Comment by rjlasko** [comment]
Also found that adding to the `disk` group does not give enough access.   While i haven't run across the panic, this is what i see when trying to run `smartctl` as a user that is a member of the `disk` group:
```
$ sudo -u smartctl-exporter id
uid=998(smartctl-exporter) gid=100(users) groups=100(users),6(disk),998(smartctl-exporter)

$ sudo -u smartctl-exporter smartctl --all /dev/sda
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-6.0.12-76060006-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org


Probable ATA device behind a SAT layer
Try an additional '-d ata' or '-d sat' argument.

$ sudo -u root smartctl --all /dev/sda
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-6.0.12-76060006-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Seagate IronWolf
```

**Comment by k0ste** [comment]
Can't reproduce on last release

```
[k0ste@k0ste bin]$ ./smartctl_exporter
ts=2023-07-29T11:58:41.678Z caller=main.go:90 level=info msg="Starting smartctl_exporter" version="(version=0.9.1, branch=master, revision=54bc9980c2075b664058b6fc36cab91a1d523c59)"
ts=2023-07-29T11:58:41.678Z caller=main.go:91 level=info msg="Build context" build_context="(go=go1.20.6, user=k0ste@k0ste.ru, date=20230729-15:47:37)"
ts=2023-07-29T11:58:41.694Z caller=main.go:119 level=info msg="No devices specified, trying to load them automatically"
ts=2023-07-29T11:58:41.707Z caller=readjson.go:69 level=warn msg="S.M.A.R.T. output reading" err="exit status 2"
ts=2023-07-29T11:58:41.707Z caller=readjson.go:123 level=error msg="Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode"
ts=2023-07-29T11:58:41.707Z caller=readjson.go:155 level=error msg="Smartctl open device: /dev/sda failed: Permission denied"
ts=2023-07-29T11:58:41.720Z caller=readjson.go:69 level=warn msg="S.M.A.R.T. output reading" err="exit status 2"
ts=2023-07-29T11:58:41.720Z caller=readjson.go:123 level=error msg="Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode"
ts=2023-07-29T11:58:41.720Z caller=readjson.go:155 level=error msg="Smartctl open device: /dev/sdb failed: Permission denied"
ts=2023-07-29T11:58:41.741Z caller=readjson.go:69 level=warn msg="S.M.A.R.T. output reading" err="exit status 2"
ts=2023-07-29T11:58:41.741Z caller=readjson.go:123 level=error msg="Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode"
ts=2023-07-29T11:58:41.741Z caller=readjson.go:155 level=error msg="Smartctl open device: /dev/sdc failed: Permission denied"
ts=2023-07-29T11:58:41.755Z caller=readjson.go:69 level=warn msg="S.M.A.R.T. output reading" err="exit status 2"
ts=2023-07-29T11:58:41.755Z caller=readjson.go:123 level=error msg="Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode"
ts=2023-07-29T11:58:41.755Z caller=readjson.go:155 level=error msg="Smartctl open device: /dev/sdd failed: Permission denied"
ts=2023-07-29T11:58:41.768Z caller=readjson.go:69 level=warn msg="S.M.A.R.T. output reading" err="exit status 2"
ts=2023-07-29T11:58:41.768Z caller=readjson.go:123 level=error msg="Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode"
ts=2023-07-29T11:58:41.768Z caller=readjson.go:155 level=error msg="Smartctl open device: /dev/nvme0 failed: Permission denied"
ts=2023-07-29T11:58:41.768Z caller=tls_config.go:232 level=info msg="Listening on" address=[::]:9633
ts=2023-07-29T11:58:41.768Z caller=tls_config.go:235 level=info msg="TLS is disabled." http2=false address=[::]:9633
```

**Comment by NiceGuyIT** [comment]
Hi @prologic, the latest `smartctl_exporter` handles the lack-of-permission gracefully. If the `smartctl_exporter` panics, please open a new issue.

---

@rjlasko and @DaAwesomeP, I started a troubleshooting document and I'm looking for feedback. The [last comment](https://github.com/prometheus-community/smartctl_exporter/issues/157#issuecomment-1694495918) explains why adding a user to the `disk` group is not sufficient for `smartctl`. If you want to improve the security while still giving `smartctl` root access, join the discussion in #146.
